name:                lineageos-history
version:             0.1.0.0
github:              "mejgun/lineageos-history"
license:             BSD3
author:              "mejgun"
maintainer:          "example@example.com"
copyright:           "mejgun"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mejgun/lineageos-history#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- time
- process
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  lineageos-history-exe:
    main:                Main.hs
    default-language: GHC2021
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lineageos-history

tests:
  lineageos-history-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lineageos-history
